using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UCR.ECCI.PI.ThemePark.Backend.Domain.Entities;

/// <summary>
/// Represents a learning space in a building of the theme park UCR.
/// </summary>
public class LearningSpace
{
    // Static counter for generating sequential IDs in memory (for testing)
    private static int _idCounter = 0;

    /// <summary>
    /// Unique internal identifier for the learning space (auto-generated by database).
    /// </summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int LearningSpaceId { get; set; }

    /// <summary>
    /// Type of the learning space (e.g., Classroom, Auditorium, Laboratory).
    /// </summary>
    public string Type { get; set; }

    /// <summary>
    /// Height of the learning space in meters.
    /// </summary>
    public float Height { get; set; }

    /// <summary>
    /// Width of the learning space in meters.
    /// </summary>
    public float Width { get; set; }

    /// <summary>
    /// Length of the learning space in meters.
    /// </summary>
    public float Length { get; set; }

    /// <summary>
    /// Parameterless constructor for EF Core.
    /// </summary>
    public LearningSpace()
    {
        Type = string.Empty;
    }

    /// <summary>
    /// Constructor for the LearningSpace class.
    /// </summary>
    /// <param name="type">Type of the learning space</param>
    /// <param name="height">Height of the learning space in meters</param>
    /// <param name="width">Width of the learning space in meters</param>
    /// <param name="length">Length of the learning space in meters</param>
    public LearningSpace(string type, float height, float width, float length)
    {
        // Validate type
        if (string.IsNullOrWhiteSpace(type))
        {
            throw new ArgumentException("Type is required", nameof(type));
        }

        var validTypes = new[] { "Classroom", "Auditorium", "Laboratory" };
        if (!validTypes.Contains(type))
        {
            throw new ArgumentException("Type must be Classroom, Auditorium, or Laboratory", nameof(type));
        }

        // Validate dimensions
        if (height <= 0)
        {
            throw new ArgumentException("Height must be positive and non-zero", nameof(height));
        }

        if (width <= 0)
        {
            throw new ArgumentException("Width must be positive and non-zero", nameof(width));
        }

        if (length <= 0)
        {
            throw new ArgumentException("Length must be positive and non-zero", nameof(length));
        }

        // Generate sequential ID for in-memory usage (EF will override with database value)
        LearningSpaceId = System.Threading.Interlocked.Increment(ref _idCounter);

        Type = type;
        Height = height;
        Width = width;
        Length = length;
    }
}
