using UCR.ECCI.PI.ThemePark.Backend.Application.Services;
using UCR.ECCI.PI.ThemePark.Backend.Domain.Exceptions;
using UCR.ECCI.PI.ThemePark.Backend.Presentation.Api.Dtos;
using UCR.ECCI.PI.ThemePark.Backend.Presentation.Api.Responses;

namespace UCR.ECCI.PI.ThemePark.Backend.Presentation.Api.Handlers;

/// <summary>
/// Handler for creating a new learning component.
/// </summary>
public static class CreateLearningComponentHandler
{
    /// <summary>
    /// Handles the asynchronous request to create a new learning component.
    /// </summary>
    /// <param name="service">The learning component service.</param>
    /// <param name="dto">The data transfer object containing the creation parameters.</param>
    /// <returns>A <see cref="CreateLearningComponentResponse"/> with the result of the operation.</returns>
    public static async Task<CreateLearningComponentResponse> HandleAsync(
        ILearningComponentService service,
        CreateLearningComponentDto dto)
    {
        try
        {
            var component = await service.CreateComponentAsync(ToRequest(dto));
            return CreateSuccessResponse(component.ComponentId, dto.ComponentId is null);
        }
        catch (DuplicateIdException ex)
        {
            return new CreateLearningComponentResponse(null, null, 409, ex.Message);
        }
        catch (ValidationException ex)
        {
            return new CreateLearningComponentResponse(null, null, 400, ex.Message);
        }
    }

    private static CreateComponentRequest ToRequest(CreateLearningComponentDto dto) =>
        new(dto.ComponentId, dto.LearningSpaceId, dto.Width, dto.Height,
            dto.Depth, dto.X, dto.Y, dto.Z, dto.Orientation);

    private static CreateLearningComponentResponse CreateSuccessResponse(string componentId, bool autoGenerated)
    {
        var message = autoGenerated
            ? "Component created with auto-generated ID"
            : "Component created successfully";
        return new CreateLearningComponentResponse(componentId, message, 201, null);
    }
}
