using UCR.ECCI.PI.ThemePark.Backend.Application.Services;
using UCR.ECCI.PI.ThemePark.Backend.Domain.Exceptions;
using UCR.ECCI.PI.ThemePark.Backend.Presentation.Api.Dtos;
using UCR.ECCI.PI.ThemePark.Backend.Presentation.Api.Responses;

namespace UCR.ECCI.PI.ThemePark.Backend.Presentation.Api.Handlers;

/// <summary>
/// Handler for creating a new learning component.
/// </summary>
public class CreateLearningComponentHandler
{
    private readonly ILearningComponentService _learningComponentService;

    /// <summary>
    /// Initializes a new instance of the <see cref="CreateLearningComponentHandler"/> class.
    /// </summary>
    /// <param name="learningComponentService">The learning component service dependency.</param>
    public CreateLearningComponentHandler(ILearningComponentService learningComponentService)
    {
        _learningComponentService = learningComponentService;
    }

    /// <summary>
    /// Handles the asynchronous request to create a new learning component.
    /// </summary>
    /// <param name="dto">The data transfer object containing the component data.</param>
    /// <returns>A <see cref="CreateComponentResponse"/> with the result of the operation.</returns>
    public async Task<CreateComponentResponse> HandleAsync(CreateLearningComponentDto dto)
    {
        try
        {
            var request = new CreateComponentRequest(
                ComponentId: dto.ComponentId,
                LearningSpaceId: dto.LearningSpaceId,
                Width: dto.Width,
                Height: dto.Height,
                Depth: dto.Depth,
                X: dto.X,
                Y: dto.Y,
                Z: dto.Z,
                Orientation: dto.Orientation);

            var component = await _learningComponentService.CreateComponentAsync(request);

            var wasAutoGenerated = string.IsNullOrEmpty(dto.ComponentId);
            var message = wasAutoGenerated
                ? "Component created successfully with an auto-generated ID."
                : "Component created successfully.";

            return new CreateComponentResponse(
                ComponentId: component.ComponentId,
                Message: message,
                StatusCode: 201,
                ErrorMessage: null);
        }
        catch (DuplicateIdException ex)
        {
            return new CreateComponentResponse(
                ComponentId: null,
                Message: null,
                StatusCode: 409,
                ErrorMessage: ex.Message);
        }
        catch (ValidationException ex)
        {
            return new CreateComponentResponse(
                ComponentId: null,
                Message: null,
                StatusCode: 400,
                ErrorMessage: ex.Message);
        }
    }
}
