using Microsoft.AspNetCore.Http;
using UCR.ECCI.PI.ThemePark.Backend.Application.Services;
using UCR.ECCI.PI.ThemePark.Backend.Domain.Exceptions;
using UCR.ECCI.PI.ThemePark.Backend.Presentation.Api.Responses;

namespace UCR.ECCI.PI.ThemePark.Backend.Presentation.Api.Handlers;

/// <summary>
/// Factory for creating HTTP responses for the create learning component operation.
/// </summary>
internal static class CreateLearningComponentResponseFactory
{
    /// <summary>
    /// Creates the appropriate HTTP result for a create-component request.
    /// </summary>
    public static async Task<IResult> CreateResponseAsync(
        ILearningComponentService service,
        CreateComponentRequest request)
    {
        try
        {
            var response = await service.CreateComponentAsync(request);
            var autoGenerated = string.IsNullOrEmpty(request.ComponentId);
            return Results.Ok(new CreateLearningComponentResponse(response.ComponentId, autoGenerated));
        }
        catch (DuplicateIdException ex)
        {
            return Results.Conflict(new ErrorResponse(ex.Message));
        }
        catch (ValidationException ex)
        {
            return Results.BadRequest(new ErrorResponse(ex.Message));
        }
    }
}
