using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using UCR.ECCI.PI.ThemePark.Backend.Application.Services;
using UCR.ECCI.PI.ThemePark.Backend.Domain.Entities;
using UCR.ECCI.PI.ThemePark.Backend.Presentation.Api.Dtos;
using UCR.ECCI.PI.ThemePark.Backend.Presentation.Api.Responses;
using UCR.ECCI.PI.ThemePark.Backend.Presentation.Api.Validators;

namespace UCR.ECCI.PI.ThemePark.Backend.Presentation.Api.Handlers;

/// <summary>
/// Handler for creating a new person.
/// </summary>
public static class CreatePersonHandler
{
    /// <summary>
    /// Handles the asynchronous request to create a new person.
    /// </summary>
    /// <param name="service">The person service.</param>
    /// <param name="dto">The data transfer object containing the creation parameters.</param>
    /// <returns>
    /// A result containing either:
    /// - <see cref="Ok{T}"/> with <see cref="CreatePersonResponse"/> on success
    /// - <see cref="BadRequest{T}"/> with <see cref="ValidationErrorResponse"/> on validation failure
    /// - <see cref="Conflict{T}"/> with <see cref="ErrorResponse"/> on duplicate person
    /// </returns>
    public static async Task<Results<Ok<CreatePersonResponse>, BadRequest<ValidationErrorResponse>, Conflict<ErrorResponse>>> HandleAsync(
        IPersonService service,
        CreatePersonDto dto)
    {
        // Validate the DTO
        var validator = new CreatePersonDtoValidator();
        var validationResult = validator.Validate(dto);

        if (!validationResult.IsValid)
        {
            var errors = validationResult.Errors.Select(e => e.ErrorMessage).ToList();
            return TypedResults.BadRequest(new ValidationErrorResponse(errors));
        }

        // Create the person entity
        var person = new Person(
            0, // ID will be generated by the database
            dto.FirstName,
            dto.LastName,
            dto.Email,
            dto.IdentityNumber,
            dto.BirthDate,
            dto.Phone);

        // Call the service to create the person
        var result = await service.CreatePersonAsync(person);

        if (!result.IsSuccess)
        {
            return TypedResults.Conflict(new ErrorResponse(result.ErrorMessage!));
        }

        var response = new CreatePersonResponse(
            true,
            result.Value!.Id,
            "Person created successfully.");

        return TypedResults.Ok(response);
    }
}
