using UCR.ECCI.PI.ThemePark.Backend.Application.Exceptions;
using UCR.ECCI.PI.ThemePark.Backend.Domain.Entities;
using UCR.ECCI.PI.ThemePark.Backend.Domain.Repositories;
using UCR.ECCI.PI.ThemePark.Backend.Domain.Services;

namespace UCR.ECCI.PI.ThemePark.Backend.Application.Services.Implementations;

/// <summary>
/// Service implementation for managing learning component data.
/// </summary>
internal class LearningComponentService : ILearningComponentService
{
    private readonly ILearningComponentRepository _learningComponentRepository;
    private readonly IComponentIdGenerator _idGenerator;

    /// <summary>
    /// Initializes a new instance of the <see cref="LearningComponentService"/> class.
    /// </summary>
    /// <param name="learningComponentRepository">The learning component repository dependency.</param>
    /// <param name="idGenerator">The component ID generator.</param>
    public LearningComponentService(ILearningComponentRepository learningComponentRepository, IComponentIdGenerator idGenerator)
    {
        _learningComponentRepository = learningComponentRepository;
        _idGenerator = idGenerator;
    }

    /// <summary>
    /// Retrieves all learning components that belong to the specified learning space.
    /// </summary>
    /// <param name="learningSpaceId">The identifier of the learning space.</param>
    /// <returns>A list of learning components belonging to the specified learning space.</returns>
    /// <exception cref="ArgumentException">Thrown when learningSpaceId is null or empty.</exception>
    public Task<List<LearningComponent>> GetComponentsByLearningSpaceIdAsync(string learningSpaceId)
    {
        if (string.IsNullOrEmpty(learningSpaceId))
            throw new ArgumentException("Learning space ID cannot be null or empty.", nameof(learningSpaceId));

        return _learningComponentRepository.GetComponentsByLearningSpaceIdAsync(learningSpaceId);
    }

    /// <summary>
    /// Creates a new learning component. If no explicit ID is provided, one is auto-generated.
    /// </summary>
    /// <param name="request">The creation request containing component details.</param>
    /// <returns>A result containing the created component ID and a status message.</returns>
    /// <exception cref="ValidationException">Thrown when validation fails.</exception>
    /// <exception cref="DuplicateIdException">Thrown when the component ID already exists.</exception>
    public async Task<CreateComponentResult> CreateComponentAsync(CreateComponentRequest request)
    {
        string componentId;
        bool isAutoGenerated;

        if (!string.IsNullOrEmpty(request.ComponentId))
        {
            componentId = request.ComponentId;
            isAutoGenerated = false;

            if (await _learningComponentRepository.ExistsAsync(componentId))
            {
                throw new DuplicateIdException($"Component ID {componentId} already exists.");
            }
        }
        else
        {
            do
            {
                componentId = await _idGenerator.GenerateIdAsync();
            }
            while (await _learningComponentRepository.ExistsAsync(componentId));

            isAutoGenerated = true;
        }

        try
        {
            var component = new LearningComponent(
                componentId,
                request.LearningSpaceId,
                request.Width,
                request.Height,
                request.Depth,
                request.X,
                request.Y,
                request.Z,
                request.Orientation);

            await _learningComponentRepository.AddAsync(component);

            var message = isAutoGenerated
                ? "Component created with auto-generated ID"
                : "Component created";

            return new CreateComponentResult(componentId, message);
        }
        catch (ArgumentException ex)
        {
            throw new ValidationException(ex.Message);
        }
    }
}
