// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AddBuildingDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The area property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Models.AddBuildingAreaDto? Area { get; set; }
#nullable restore
#else
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Models.AddBuildingAreaDto Area { get; set; }
#endif
        /// <summary>The color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Color { get; set; }
#nullable restore
#else
        public string Color { get; set; }
#endif
        /// <summary>The height property</summary>
        public double? Height { get; set; }
        /// <summary>The length property</summary>
        public double? Length { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The width property</summary>
        public double? Width { get; set; }
        /// <summary>The x property</summary>
        public double? X { get; set; }
        /// <summary>The y property</summary>
        public double? Y { get; set; }
        /// <summary>The z property</summary>
        public double? Z { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Models.AddBuildingDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Models.AddBuildingDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Models.AddBuildingDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "area", n => { Area = n.GetObjectValue<global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Models.AddBuildingAreaDto>(global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Models.AddBuildingAreaDto.CreateFromDiscriminatorValue); } },
                { "color", n => { Color = n.GetStringValue(); } },
                { "height", n => { Height = n.GetDoubleValue(); } },
                { "length", n => { Length = n.GetDoubleValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "width", n => { Width = n.GetDoubleValue(); } },
                { "x", n => { X = n.GetDoubleValue(); } },
                { "y", n => { Y = n.GetDoubleValue(); } },
                { "z", n => { Z = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Models.AddBuildingAreaDto>("area", Area);
            writer.WriteStringValue("color", Color);
            writer.WriteDoubleValue("height", Height);
            writer.WriteDoubleValue("length", Length);
            writer.WriteStringValue("name", Name);
            writer.WriteDoubleValue("width", Width);
            writer.WriteDoubleValue("x", X);
            writer.WriteDoubleValue("y", Y);
            writer.WriteDoubleValue("z", Z);
        }
    }
}
#pragma warning restore CS0618
