// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.AddArea;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.AddBuilding;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.AddCampus;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.AddUniversity;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Area;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Buildings;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.DeleteBuilding;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.DeleteCampus;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Floors;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.LearningComponent;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.LearningSpaces;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.ListAreas;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.ListBuilding;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.ListBuildings;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.ListCampus;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.ListUniversity;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Permission;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Person;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Role;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Staff;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Student;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.University;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.UpdateBuilding;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.User;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Users;
using UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Userwithperson;
namespace UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiClient : BaseRequestBuilder
    {
        /// <summary>The addArea property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.AddArea.AddAreaRequestBuilder AddArea
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.AddArea.AddAreaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The addBuilding property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.AddBuilding.AddBuildingRequestBuilder AddBuilding
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.AddBuilding.AddBuildingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The addCampus property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.AddCampus.AddCampusRequestBuilder AddCampus
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.AddCampus.AddCampusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The addUniversity property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.AddUniversity.AddUniversityRequestBuilder AddUniversity
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.AddUniversity.AddUniversityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The area property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Area.AreaRequestBuilder Area
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Area.AreaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The buildings property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Buildings.BuildingsRequestBuilder Buildings
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Buildings.BuildingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deleteBuilding property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.DeleteBuilding.DeleteBuildingRequestBuilder DeleteBuilding
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.DeleteBuilding.DeleteBuildingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deleteCampus property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.DeleteCampus.DeleteCampusRequestBuilder DeleteCampus
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.DeleteCampus.DeleteCampusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The floors property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Floors.FloorsRequestBuilder Floors
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Floors.FloorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The learningComponent property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.LearningComponent.LearningComponentRequestBuilder LearningComponent
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.LearningComponent.LearningComponentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The learningSpaces property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.LearningSpaces.LearningSpacesRequestBuilder LearningSpaces
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.LearningSpaces.LearningSpacesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The listAreas property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.ListAreas.ListAreasRequestBuilder ListAreas
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.ListAreas.ListAreasRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The listBuilding property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.ListBuilding.ListBuildingRequestBuilder ListBuilding
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.ListBuilding.ListBuildingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The listBuildings property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.ListBuildings.ListBuildingsRequestBuilder ListBuildings
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.ListBuildings.ListBuildingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The listCampus property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.ListCampus.ListCampusRequestBuilder ListCampus
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.ListCampus.ListCampusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The listUniversity property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.ListUniversity.ListUniversityRequestBuilder ListUniversity
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.ListUniversity.ListUniversityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The permission property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Permission.PermissionRequestBuilder Permission
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Permission.PermissionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The person property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Person.PersonRequestBuilder Person
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Person.PersonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The role property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Role.RoleRequestBuilder Role
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Role.RoleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The staff property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Staff.StaffRequestBuilder Staff
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Staff.StaffRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The student property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Student.StudentRequestBuilder Student
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Student.StudentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The university property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.University.UniversityRequestBuilder University
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.University.UniversityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The updateBuilding property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.UpdateBuilding.UpdateBuildingRequestBuilder UpdateBuilding
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.UpdateBuilding.UpdateBuildingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.User.UserRequestBuilder User
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Users.UsersRequestBuilder Users
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The userwithperson property</summary>
        public global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Userwithperson.UserwithpersonRequestBuilder Userwithperson
        {
            get => new global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.Userwithperson.UserwithpersonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UCR.ECCI.PI.ThemePark.Frontend.Blazor.Infrastructure.Kiota.ApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
