using Moq;
using NUnit.Framework;
using UCR.ECCI.PI.ThemePark.Backend.Application.Exceptions;
using UCR.ECCI.PI.ThemePark.Backend.Application.Services;
using UCR.ECCI.PI.ThemePark.Backend.Domain.Entities;
using UCR.ECCI.PI.ThemePark.Backend.Presentation.Api.Handlers;
using UCR.ECCI.PI.ThemePark.Backend.Presentation.Api.Responses;

namespace UCR.ECCI.PI.ThemePark.Backend.Presentation.Tests.Unit;

/// <summary>
/// Unit tests for <see cref="CreateLearningComponentHandler.HandleAsync"/>.
/// Covers intents Presentation-001 through Presentation-004 from story CPD-LC-001-009.
/// </summary>
[TestFixture]
public class CreateLearningComponentHandlerTests
{
    private Mock<ILearningComponentService> _mockService = null!;
    private CreateLearningComponentHandler _sut = null!;

    // Valid test data
    private const string ValidLearningSpaceId = "LS-001";
    private const float ValidWidth = 1.5f;
    private const float ValidHeight = 1.0f;
    private const float ValidDepth = 0.5f;
    private const float ValidX = 10.0f;
    private const float ValidY = 5.0f;
    private const float ValidZ = 0.0f;
    private const string ValidOrientation = "North";

    [SetUp]
    public void SetUp()
    {
        _mockService = new Mock<ILearningComponentService>();
        _sut = new CreateLearningComponentHandler(_mockService.Object);
    }

    /// <summary>
    /// Presentation-001: Verify that creating a component without an ID
    /// returns the auto-generated ID in the response with a success message.
    /// </summary>
    [Test]
    [Description("Presentation-001: Verify that creating a component without an ID returns the auto-generated ID in the response")]
    public async Task HandleAsync_WithoutId_ReturnsAutoGeneratedId()
    {
        // Arrange
        var generatedId = "COMP-12345";
        var request = new CreateComponentRequest(
            ComponentId: null,
            LearningSpaceId: ValidLearningSpaceId,
            Width: ValidWidth,
            Height: ValidHeight,
            Depth: ValidDepth,
            X: ValidX,
            Y: ValidY,
            Z: ValidZ,
            Orientation: ValidOrientation);

        var component = new LearningComponent(
            generatedId, ValidLearningSpaceId,
            ValidWidth, ValidHeight, ValidDepth,
            ValidX, ValidY, ValidZ,
            ValidOrientation);

        _mockService
            .Setup(s => s.CreateComponentAsync(It.IsAny<CreateComponentRequest>()))
            .ReturnsAsync(component);

        // Act
        var result = await _sut.HandleAsync(request);

        // Assert
        Assert.Multiple(() =>
        {
            Assert.That(result.ComponentId, Is.EqualTo(generatedId));
            Assert.That(result.Message, Does.Contain("auto-generated"));
        });
    }

    /// <summary>
    /// Presentation-002: Verify that creating a component with an explicit ID
    /// returns the provided ID in the response.
    /// </summary>
    [Test]
    [Description("Presentation-002: Verify that creating a component with an explicit ID returns the provided ID in the response")]
    public async Task HandleAsync_WithExplicitId_ReturnsProvidedId()
    {
        // Arrange
        var explicitId = "COMP-EXPLICIT-001";
        var request = new CreateComponentRequest(
            ComponentId: explicitId,
            LearningSpaceId: ValidLearningSpaceId,
            Width: ValidWidth,
            Height: ValidHeight,
            Depth: ValidDepth,
            X: ValidX,
            Y: ValidY,
            Z: ValidZ,
            Orientation: ValidOrientation);

        var component = new LearningComponent(
            explicitId, ValidLearningSpaceId,
            ValidWidth, ValidHeight, ValidDepth,
            ValidX, ValidY, ValidZ,
            ValidOrientation);

        _mockService
            .Setup(s => s.CreateComponentAsync(It.IsAny<CreateComponentRequest>()))
            .ReturnsAsync(component);

        // Act
        var result = await _sut.HandleAsync(request);

        // Assert
        Assert.That(result.ComponentId, Is.EqualTo(explicitId));
    }

    /// <summary>
    /// Presentation-003: Verify that attempting to create a component with a duplicate ID
    /// returns a 409 Conflict response with an appropriate error message.
    /// </summary>
    [Test]
    [Description("Presentation-003: Verify that creating a component with a duplicate ID returns a 409 Conflict response")]
    public async Task HandleAsync_WithDuplicateId_ReturnsConflict()
    {
        // Arrange
        var request = new CreateComponentRequest(
            ComponentId: "COMP-DUPLICATE",
            LearningSpaceId: ValidLearningSpaceId,
            Width: ValidWidth,
            Height: ValidHeight,
            Depth: ValidDepth,
            X: ValidX,
            Y: ValidY,
            Z: ValidZ,
            Orientation: ValidOrientation);

        _mockService
            .Setup(s => s.CreateComponentAsync(It.IsAny<CreateComponentRequest>()))
            .ThrowsAsync(new DuplicateIdException("Component with ID 'COMP-DUPLICATE' already exists"));

        // Act
        var result = await _sut.HandleAsync(request);

        // Assert
        Assert.Multiple(() =>
        {
            Assert.That(result.StatusCode, Is.EqualTo(409));
            Assert.That(result.ErrorMessage, Does.Contain("already exists"));
        });
    }

    /// <summary>
    /// Presentation-004: Verify that creating a component with invalid data
    /// returns a 400 Bad Request response with an appropriate error message.
    /// </summary>
    [Test]
    [Description("Presentation-004: Verify that creating a component with invalid data returns a 400 Bad Request response")]
    public async Task HandleAsync_WithInvalidData_ReturnsBadRequest()
    {
        // Arrange
        var request = new CreateComponentRequest(
            ComponentId: null,
            LearningSpaceId: ValidLearningSpaceId,
            Width: -1.5f,
            Height: ValidHeight,
            Depth: ValidDepth,
            X: ValidX,
            Y: ValidY,
            Z: ValidZ,
            Orientation: ValidOrientation);

        _mockService
            .Setup(s => s.CreateComponentAsync(It.IsAny<CreateComponentRequest>()))
            .ThrowsAsync(new ValidationException("Width must be positive"));

        // Act
        var result = await _sut.HandleAsync(request);

        // Assert
        Assert.Multiple(() =>
        {
            Assert.That(result.StatusCode, Is.EqualTo(400));
            Assert.That(result.ErrorMessage, Does.Contain("Width"));
        });
    }
}
