using Moq;
using NUnit.Framework;
using UCR.ECCI.PI.ThemePark.Backend.Application.Services;
using UCR.ECCI.PI.ThemePark.Backend.Domain.Entities;
using UCR.ECCI.PI.ThemePark.Backend.Domain.Exceptions;
using UCR.ECCI.PI.ThemePark.Backend.Presentation.Api.Handlers;

namespace UCR.ECCI.PI.ThemePark.Backend.Presentation.Tests.Unit;

/// <summary>
/// Unit tests for <see cref="CreateLearningComponentHandler.HandleAsync"/>.
/// Covers intents Presentation-001 through Presentation-004.
/// </summary>
[TestFixture]
public class CreateLearningComponentHandlerTests
{
    private Mock<ILearningComponentService> _mockService = null!;
    private CreateLearningComponentHandler _sut = null!;

    // Valid test data
    private const string ValidLearningSpaceId = "LS-001";
    private const float ValidWidth = 1.5f;
    private const float ValidHeight = 1.0f;
    private const float ValidDepth = 0.5f;
    private const float ValidX = 10.0f;
    private const float ValidY = 5.0f;
    private const float ValidZ = 0.0f;
    private const string ValidOrientation = "North";

    [SetUp]
    public void SetUp()
    {
        _mockService = new Mock<ILearningComponentService>();
        _sut = new CreateLearningComponentHandler(_mockService.Object);
    }

    [TearDown]
    public void TearDown()
    {
        _mockService.VerifyAll();
    }

    private static CreateComponentRequest CreateRequest(string componentId = "")
    {
        return new CreateComponentRequest(
            componentId,
            ValidLearningSpaceId,
            ValidWidth,
            ValidHeight,
            ValidDepth,
            ValidX,
            ValidY,
            ValidZ,
            ValidOrientation);
    }

    /// <summary>
    /// Presentation-001: Verify that creating a component without an ID returns
    /// the auto-generated ID in the response.
    /// </summary>
    [Test]
    [Description("Presentation-001: Handler returns auto-generated ID when request has no explicit ID")]
    public async Task HandleAsync_WithoutExplicitId_ReturnsAutoGeneratedId()
    {
        // Arrange
        var request = CreateRequest(componentId: "");
        var component = new LearningComponent("COMP-12345", ValidLearningSpaceId, ValidWidth, ValidHeight, ValidDepth, ValidX, ValidY, ValidZ, ValidOrientation);
        _mockService.Setup(s => s.CreateComponentAsync(request)).ReturnsAsync(component);

        // Act
        var result = await _sut.HandleAsync(request);

        // Assert
        Assert.Multiple(() =>
        {
            Assert.That(result.ComponentId, Is.EqualTo("COMP-12345"));
            Assert.That(result.Message, Does.Contain("auto-generated"));
        });
    }

    /// <summary>
    /// Presentation-002: Verify that creating a component with an explicit ID
    /// returns the provided ID in the response.
    /// </summary>
    [Test]
    [Description("Presentation-002: Handler returns provided explicit ID in response")]
    public async Task HandleAsync_WithExplicitId_ReturnsProvidedId()
    {
        // Arrange
        var request = CreateRequest(componentId: "COMP-EXPLICIT-001");
        var component = new LearningComponent("COMP-EXPLICIT-001", ValidLearningSpaceId, ValidWidth, ValidHeight, ValidDepth, ValidX, ValidY, ValidZ, ValidOrientation);
        _mockService.Setup(s => s.CreateComponentAsync(request)).ReturnsAsync(component);

        // Act
        var result = await _sut.HandleAsync(request);

        // Assert
        Assert.That(result.ComponentId, Is.EqualTo("COMP-EXPLICIT-001"));
    }

    /// <summary>
    /// Presentation-003: Verify that attempting to create a component with a duplicate ID
    /// returns a 409 Conflict response.
    /// </summary>
    [Test]
    [Description("Presentation-003: Handler returns 409 Conflict for duplicate ID")]
    public async Task HandleAsync_DuplicateId_ReturnsConflict()
    {
        // Arrange
        var request = CreateRequest(componentId: "COMP-DUPLICATE");
        _mockService.Setup(s => s.CreateComponentAsync(request))
            .ThrowsAsync(new DuplicateIdException("already exists"));

        // Act
        var result = await _sut.HandleAsync(request);

        // Assert
        Assert.Multiple(() =>
        {
            Assert.That(result.StatusCode, Is.EqualTo(409));
            Assert.That(result.ErrorMessage, Does.Contain("already exists"));
        });
    }

    /// <summary>
    /// Presentation-004: Verify that creating a component with invalid data
    /// returns a 400 Bad Request response.
    /// </summary>
    [Test]
    [Description("Presentation-004: Handler returns 400 Bad Request for invalid data")]
    public async Task HandleAsync_InvalidData_ReturnsBadRequest()
    {
        // Arrange
        var request = CreateRequest(componentId: "");
        _mockService.Setup(s => s.CreateComponentAsync(request))
            .ThrowsAsync(new ValidationException("Width must be positive"));

        // Act
        var result = await _sut.HandleAsync(request);

        // Assert
        Assert.Multiple(() =>
        {
            Assert.That(result.StatusCode, Is.EqualTo(400));
            Assert.That(result.ErrorMessage, Does.Contain("Width"));
        });
    }
}
