using Microsoft.AspNetCore.Http.HttpResults;
using Moq;
using NUnit.Framework;
using UCR.ECCI.PI.ThemePark.Backend.Application.Services;
using UCR.ECCI.PI.ThemePark.Backend.Domain.Entities;
using UCR.ECCI.PI.ThemePark.Backend.Domain.Exceptions;
using UCR.ECCI.PI.ThemePark.Backend.Presentation.Api.Dtos;
using UCR.ECCI.PI.ThemePark.Backend.Presentation.Api.Handlers;
using UCR.ECCI.PI.ThemePark.Backend.Presentation.Api.Responses;

namespace UCR.ECCI.PI.ThemePark.Backend.Presentation.Tests.Unit;

/// <summary>
/// Unit tests for <see cref="CreateLearningComponentHandler.HandleAsync"/>.
/// Covers intents Presentation-001 through Presentation-004 from CPD-LC-001-009.
/// </summary>
[TestFixture]
public class CreateLearningComponentHandlerTests
{
    private Mock<ILearningComponentService> _mockService = null!;

    // Valid test data
    private const string ValidLearningSpaceId = "LS-001";
    private const float ValidWidth = 1.5f;
    private const float ValidHeight = 1.0f;
    private const float ValidDepth = 0.5f;
    private const float ValidX = 10.0f;
    private const float ValidY = 5.0f;
    private const float ValidZ = 0.0f;
    private const string ValidOrientation = "North";

    [SetUp]
    public void SetUp()
    {
        _mockService = new Mock<ILearningComponentService>();
    }

    [TearDown]
    public void TearDown()
    {
        _mockService.VerifyAll();
    }

    private static CreateLearningComponentDto CreateDtoWithoutId()
    {
        return new CreateLearningComponentDto(
            ComponentId: null,
            LearningSpaceId: ValidLearningSpaceId,
            Width: ValidWidth, Height: ValidHeight, Depth: ValidDepth,
            X: ValidX, Y: ValidY, Z: ValidZ,
            Orientation: ValidOrientation);
    }

    private static CreateLearningComponentDto CreateDtoWithExplicitId(string componentId)
    {
        return new CreateLearningComponentDto(
            ComponentId: componentId,
            LearningSpaceId: ValidLearningSpaceId,
            Width: ValidWidth, Height: ValidHeight, Depth: ValidDepth,
            X: ValidX, Y: ValidY, Z: ValidZ,
            Orientation: ValidOrientation);
    }

    /// <summary>
    /// Presentation-001 (CPD-LC-001-009): Verify that creating a component without an ID
    /// returns the auto-generated ID in the response with a success message.
    /// </summary>
    [Test]
    [Description("Presentation-001 (CPD-LC-001-009): Handler returns auto-generated ID in response")]
    public async Task HandleAsync_WithoutId_ReturnsAutoGeneratedIdInResponse()
    {
        // Arrange
        var generatedId = "COMP-12345";
        var component = new LearningComponent(
            generatedId, ValidLearningSpaceId,
            ValidWidth, ValidHeight, ValidDepth,
            ValidX, ValidY, ValidZ,
            ValidOrientation);

        _mockService
            .Setup(s => s.CreateComponentAsync(It.IsAny<CreateComponentRequest>()))
            .ReturnsAsync(component);

        var dto = CreateDtoWithoutId();

        // Act
        var result = await CreateLearningComponentHandler.HandleAsync(_mockService.Object, dto);

        // Assert
        Assert.Multiple(() =>
        {
            Assert.That(result.Result, Is.InstanceOf<Ok<CreateLearningComponentResponse>>());
            var okResult = (Ok<CreateLearningComponentResponse>)result.Result;
            Assert.That(okResult.Value!.ComponentId, Is.EqualTo(generatedId));
        });
    }

    /// <summary>
    /// Presentation-002 (CPD-LC-001-009): Verify that creating a component with an explicit ID
    /// returns the provided ID in the response.
    /// </summary>
    [Test]
    [Description("Presentation-002 (CPD-LC-001-009): Handler returns explicit ID in response")]
    public async Task HandleAsync_WithExplicitId_ReturnsProvidedIdInResponse()
    {
        // Arrange
        var explicitId = "COMP-EXPLICIT-001";
        var component = new LearningComponent(
            explicitId, ValidLearningSpaceId,
            ValidWidth, ValidHeight, ValidDepth,
            ValidX, ValidY, ValidZ,
            ValidOrientation);

        _mockService
            .Setup(s => s.CreateComponentAsync(It.IsAny<CreateComponentRequest>()))
            .ReturnsAsync(component);

        var dto = CreateDtoWithExplicitId(explicitId);

        // Act
        var result = await CreateLearningComponentHandler.HandleAsync(_mockService.Object, dto);

        // Assert
        Assert.Multiple(() =>
        {
            Assert.That(result.Result, Is.InstanceOf<Ok<CreateLearningComponentResponse>>());
            var okResult = (Ok<CreateLearningComponentResponse>)result.Result;
            Assert.That(okResult.Value!.ComponentId, Is.EqualTo(explicitId));
        });
    }

    /// <summary>
    /// Presentation-003 (CPD-LC-001-009): Verify that attempting to create a component
    /// with a duplicate ID returns a 409 Conflict response.
    /// </summary>
    [Test]
    [Description("Presentation-003 (CPD-LC-001-009): Duplicate ID returns 409 Conflict")]
    public async Task HandleAsync_WithDuplicateId_ReturnsConflict()
    {
        // Arrange
        _mockService
            .Setup(s => s.CreateComponentAsync(It.IsAny<CreateComponentRequest>()))
            .ThrowsAsync(new DuplicateIdException("Component with ID 'COMP-EXISTING' already exists"));

        var dto = CreateDtoWithExplicitId("COMP-EXISTING");

        // Act
        var result = await CreateLearningComponentHandler.HandleAsync(_mockService.Object, dto);

        // Assert
        Assert.Multiple(() =>
        {
            Assert.That(result.Result, Is.InstanceOf<Conflict<string>>());
            var conflictResult = (Conflict<string>)result.Result;
            Assert.That(conflictResult.Value, Does.Contain("already exists"));
        });
    }

    /// <summary>
    /// Presentation-004 (CPD-LC-001-009): Verify that creating a component with invalid data
    /// returns a 400 Bad Request response with the validation error message.
    /// </summary>
    [Test]
    [Description("Presentation-004 (CPD-LC-001-009): Invalid data returns 400 Bad Request")]
    public async Task HandleAsync_WithInvalidData_ReturnsBadRequest()
    {
        // Arrange
        _mockService
            .Setup(s => s.CreateComponentAsync(It.IsAny<CreateComponentRequest>()))
            .ThrowsAsync(new ValidationException("Width must be positive"));

        var dto = new CreateLearningComponentDto(
            ComponentId: null,
            LearningSpaceId: ValidLearningSpaceId,
            Width: -1.5f, Height: ValidHeight, Depth: ValidDepth,
            X: ValidX, Y: ValidY, Z: ValidZ,
            Orientation: ValidOrientation);

        // Act
        var result = await CreateLearningComponentHandler.HandleAsync(_mockService.Object, dto);

        // Assert
        Assert.Multiple(() =>
        {
            Assert.That(result.Result, Is.InstanceOf<BadRequest<string>>());
            var badRequestResult = (BadRequest<string>)result.Result;
            Assert.That(badRequestResult.Value, Does.Contain("Width"));
        });
    }
}
