namespace UCR.ECCI.PI.ThemePark.Backend.Presentation.Api.Responses;

/// <summary>
/// Response object for a successfully created learning component.
/// </summary>
public class CreateLearningComponentResponse
{
    /// <summary>
    /// The identifier of the created component.
    /// </summary>
    public string ComponentId { get; }

    /// <summary>
    /// A message describing the outcome of the creation.
    /// </summary>
    public string Message { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="CreateLearningComponentResponse"/> class.
    /// </summary>
    /// <param name="componentId">The component identifier.</param>
    /// <param name="autoGenerated">Whether the ID was auto-generated.</param>
    public CreateLearningComponentResponse(string componentId, bool autoGenerated)
    {
        ComponentId = componentId;
        Message = autoGenerated
            ? $"Component created successfully with auto-generated ID '{componentId}'."
            : $"Component created successfully with ID '{componentId}'.";
    }
}
