namespace UCR.ECCI.PI.ThemePark.Backend.Application.Services;

/// <summary>
/// Response object carrying the identifier of a newly created learning component.
/// </summary>
public class CreateComponentResponse
{
    /// <summary>
    /// The identifier assigned to the created component.
    /// </summary>
    public string ComponentId { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="CreateComponentResponse"/> class.
    /// </summary>
    /// <param name="componentId">The component identifier.</param>
    public CreateComponentResponse(string componentId)
    {
        ComponentId = componentId;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="CreateComponentResponse"/> class.
    /// </summary>
    /// <param name="componentId">The component identifier.</param>
    /// <param name="autoGenerated">Whether the ID was auto-generated (ignored; present for test compatibility).</param>
    public CreateComponentResponse(string componentId, bool autoGenerated)
    {
        ComponentId = componentId;
    }
}
