namespace UCR.ECCI.PI.ThemePark.Backend.Presentation.Dtos.AccountManagement;

/// <summary>
/// Represents a Data Transfer Object (DTO) for a person,
/// including the database-generated unique identifier.
/// </summary>
/// <param name="Id">The unique identifier of the person.</param>
/// <param name="Email">The email address of the person.</param>
/// <param name="FirstName">The first name of the person.</param>
/// <param name="LastName">The last name of the person.</param>
/// <param name="Phone">The phone number of the person.</param>
/// <param name="BirthDate">The birth date of the person as a <see cref="DateOnly"/>.</param>
/// <param name="IdentityNumber">The identity number (e.g., national ID) of the person.</param>
public record class PersonDto(
  int Id,
  string Email,
  string FirstName,
  string LastName,
  string Phone,
  DateOnly BirthDate,
  string IdentityNumber
);

/// <summary>
/// Represents a Data Transfer Object (DTO) used for creating a new person.
/// This class omits the Id since it is usually generated by the system.
/// </summary>
/// <param name="Email">The email address of the person.</param>
/// <param name="FirstName">The first name of the person.</param>
/// <param name="LastName">The last name of the person.</param>
/// <param name="Phone">The phone number of the person.</param>
/// <param name="BirthDate">The birth date of the person as a <see cref="DateOnly"/>.</param>
/// <param name="IdentityNumber">The identity number (e.g., national ID) of the person.</param>
public record class CreatePersonDto(
  string Email,
  string FirstName,
  string LastName,
  string Phone,
  DateOnly BirthDate,
  string IdentityNumber
);
