namespace UCR.ECCI.PI.ThemePark.Backend.Presentation.Dtos.AccountManagement;

/// <summary>
/// Represents a Data Transfer Object (DTO) for a Student,
/// including the database-generated unique identifier.
/// </summary>
/// <param name="Id">The unique identifier of the Student.</param>
/// <param name="Email">The email address of the Student.</param>
/// <param name="FirstName">The first name of the Student.</param>
/// <param name="LastName">The last name of the Student.</param>
/// <param name="Phone">The phone number of the Student.</param>
/// <param name="BirthDate">The birth date of the person as a <see cref="DateOnly"/>.</param>
/// <param name="IdentityNumber">The identity number (e.g., national ID) of the person.</param>
public record class StudentDto(
  int PersonId,
  string StudentId,
  string Email,
  string FirstName,
  string LastName,
  string Phone,
  DateOnly BirthDate,
  string IdentityNumber,
  string InstitutionalEmail

);

/// <summary>
/// Represents a Data Transfer Object (DTO) used for creating a new Student.
/// This class omits the Id since it is usually generated by the system.
/// </summary>
/// <param name="Email">The email address of the Student.</param>
/// <param name="FirstName">The first name of the Student.</param>
/// <param name="LastName">The last name of the Student.</param>
/// <param name="Phone">The phone number of the Student.</param>
/// <param name="BirthDate">The birth date of the Student as a <see cref="DateOnly"/>.</param>
/// <param name="IdentityNumber">The identity number (e.g., national ID) of the Student.</param>
public record class CreateStudentDto(
  string StudentId,
  string Email,
  string FirstName,
  string LastName,
  string Phone,
  DateOnly BirthDate,
  string IdentityNumber,
  string InstitutionalEmail
);
