CREATE TABLE [dbo].[LearningSpace]
(
	[LearningSpaceId] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Type] NVARCHAR(50) NOT NULL,
	[Height] FLOAT NOT NULL,
	[Width] FLOAT NOT NULL,
	[Length] FLOAT NOT NULL
)
