CREATE TABLE Person (
  Id INT PRIMARY KEY IDENTITY,
  Email NVARCHAR(100) UNIQUE NOT NULL,
  IdentityNumber VARCHAR(20) UNIQUE NOT NULL,
  FirstName NVARCHAR(50) NOT NULL,
  LastName NVARCHAR(50) NOT NULL,
  BirthDate DATE NOT NULL,
  Phone VARCHAR(20) NULL
);