CREATE TABLE Student (
  PersonId INT NOT NULL PRIMARY KEY,
  StudentId VARCHAR(30) NOT NULL UNIQUE,
  InstitutionalEmail NVARCHAR(100) UNIQUE NOT NULL,
  FOREIGN KEY (PersonId) REFERENCES Person(Id) ON DELETE CASCADE
);
