using NUnit.Framework;
using UCR.ECCI.PI.ThemePark.Backend.Domain.Entities;

namespace UCR.ECCI.PI.ThemePark.Backend.Domain.Tests.Unit;

/// <summary>
/// Unit tests for the <see cref="LearningComponent"/> entity constructor and validation.
/// Covers intents Domain-001 through Domain-014 for story CPD-LC-001-009.
/// </summary>
[TestFixture]
public class LearningComponentConstructorTests
{
    private const string ValidLearningSpaceId = "LS-001";
    private const float ValidWidth = 1.5f;
    private const float ValidHeight = 1.0f;
    private const float ValidDepth = 0.5f;
    private const float ValidX = 10.0f;
    private const float ValidY = 5.0f;
    private const float ValidZ = 0.0f;
    private const string ValidOrientation = "North";

    /// <summary>
    /// Domain-001: Verify that a LearningComponent can be created with an auto-generated ID when no ID is provided.
    /// </summary>
    [Test]
    [Description("Domain-001: Verify that a LearningComponent can be created with an auto-generated ID when no ID is provided")]
    public void Constructor_WithAutoGeneratedId_SetsId()
    {
        // Arrange & Act
        var component = new LearningComponent(learningSpaceId: ValidLearningSpaceId, width: ValidWidth, height: ValidHeight, depth: ValidDepth, x: ValidX, y: ValidY, z: ValidZ, orientation: ValidOrientation);

        // Assert
        Assert.That(component.ComponentId, Is.Not.Null);
        Assert.That(component.ComponentId, Is.Not.Empty);
    }

    /// <summary>
    /// Domain-002: Verify that a LearningComponent can be created with an explicitly provided ID.
    /// </summary>
    [Test]
    [Description("Domain-002: Verify that a LearningComponent can be created with an explicitly provided ID")]
    public void Constructor_WithExplicitId_SetsId()
    {
        // Arrange & Act
        var component = new LearningComponent(componentId: "COMP-12345", learningSpaceId: ValidLearningSpaceId, width: ValidWidth, height: ValidHeight, depth: ValidDepth, x: ValidX, y: ValidY, z: ValidZ, orientation: ValidOrientation);

        // Assert
        Assert.That(component.ComponentId, Is.EqualTo("COMP-12345"));
    }

    /// <summary>
    /// Domain-003: Verify that creating a LearningComponent with negative width throws an ArgumentException.
    /// </summary>
    [Test]
    [Description("Domain-003: Verify that creating a LearningComponent with negative width throws an ArgumentException")]
    public void Constructor_WithNegativeWidth_ThrowsArgumentException()
    {
        // Arrange & Act & Assert
        var ex = Assert.Throws<ArgumentException>(() => new LearningComponent(learningSpaceId: ValidLearningSpaceId, width: -1.5f, height: ValidHeight, depth: ValidDepth, x: ValidX, y: ValidY, z: ValidZ, orientation: ValidOrientation));
        Assert.That(ex!.ParamName, Is.EqualTo("width"));
    }

    /// <summary>
    /// Domain-004: Verify that creating a LearningComponent with zero width throws an ArgumentException.
    /// </summary>
    [Test]
    [Description("Domain-004: Verify that creating a LearningComponent with zero width throws an ArgumentException")]
    public void Constructor_WithZeroWidth_ThrowsArgumentException()
    {
        // Arrange & Act & Assert
        var ex = Assert.Throws<ArgumentException>(() => new LearningComponent(learningSpaceId: ValidLearningSpaceId, width: 0.0f, height: ValidHeight, depth: ValidDepth, x: ValidX, y: ValidY, z: ValidZ, orientation: ValidOrientation));
        Assert.That(ex!.ParamName, Is.EqualTo("width"));
    }

    /// <summary>
    /// Domain-005: Verify that creating a LearningComponent with negative height throws an ArgumentException.
    /// </summary>
    [Test]
    [Description("Domain-005: Verify that creating a LearningComponent with negative height throws an ArgumentException")]
    public void Constructor_WithNegativeHeight_ThrowsArgumentException()
    {
        // Arrange & Act & Assert
        var ex = Assert.Throws<ArgumentException>(() => new LearningComponent(learningSpaceId: ValidLearningSpaceId, width: ValidWidth, height: -1.0f, depth: ValidDepth, x: ValidX, y: ValidY, z: ValidZ, orientation: ValidOrientation));
        Assert.That(ex!.ParamName, Is.EqualTo("height"));
    }

    /// <summary>
    /// Domain-006: Verify that creating a LearningComponent with negative depth throws an ArgumentException.
    /// </summary>
    [Test]
    [Description("Domain-006: Verify that creating a LearningComponent with negative depth throws an ArgumentException")]
    public void Constructor_WithNegativeDepth_ThrowsArgumentException()
    {
        // Arrange & Act & Assert
        var ex = Assert.Throws<ArgumentException>(() => new LearningComponent(learningSpaceId: ValidLearningSpaceId, width: ValidWidth, height: ValidHeight, depth: -0.5f, x: ValidX, y: ValidY, z: ValidZ, orientation: ValidOrientation));
        Assert.That(ex!.ParamName, Is.EqualTo("depth"));
    }

    /// <summary>
    /// Domain-007: Verify that creating a LearningComponent with negative X coordinate throws an ArgumentException.
    /// </summary>
    [Test]
    [Description("Domain-007: Verify that creating a LearningComponent with negative X coordinate throws an ArgumentException")]
    public void Constructor_WithNegativeX_ThrowsArgumentException()
    {
        // Arrange & Act & Assert
        var ex = Assert.Throws<ArgumentException>(() => new LearningComponent(learningSpaceId: ValidLearningSpaceId, width: ValidWidth, height: ValidHeight, depth: ValidDepth, x: -10.0f, y: ValidY, z: ValidZ, orientation: ValidOrientation));
        Assert.That(ex!.ParamName, Is.EqualTo("x"));
    }

    /// <summary>
    /// Domain-008: Verify that creating a LearningComponent with negative Y coordinate throws an ArgumentException.
    /// </summary>
    [Test]
    [Description("Domain-008: Verify that creating a LearningComponent with negative Y coordinate throws an ArgumentException")]
    public void Constructor_WithNegativeY_ThrowsArgumentException()
    {
        // Arrange & Act & Assert
        var ex = Assert.Throws<ArgumentException>(() => new LearningComponent(learningSpaceId: ValidLearningSpaceId, width: ValidWidth, height: ValidHeight, depth: ValidDepth, x: ValidX, y: -5.0f, z: ValidZ, orientation: ValidOrientation));
        Assert.That(ex!.ParamName, Is.EqualTo("y"));
    }

    /// <summary>
    /// Domain-009: Verify that creating a LearningComponent with negative Z coordinate throws an ArgumentException.
    /// </summary>
    [Test]
    [Description("Domain-009: Verify that creating a LearningComponent with negative Z coordinate throws an ArgumentException")]
    public void Constructor_WithNegativeZ_ThrowsArgumentException()
    {
        // Arrange & Act & Assert
        var ex = Assert.Throws<ArgumentException>(() => new LearningComponent(learningSpaceId: ValidLearningSpaceId, width: ValidWidth, height: ValidHeight, depth: ValidDepth, x: ValidX, y: ValidY, z: -1.0f, orientation: ValidOrientation));
        Assert.That(ex!.ParamName, Is.EqualTo("z"));
    }

    /// <summary>
    /// Domain-010: Verify that creating a LearningComponent with invalid orientation throws an ArgumentException.
    /// </summary>
    [Test]
    [Description("Domain-010: Verify that creating a LearningComponent with invalid orientation throws an ArgumentException")]
    public void Constructor_WithInvalidOrientation_ThrowsArgumentException()
    {
        // Arrange & Act & Assert
        var ex = Assert.Throws<ArgumentException>(() => new LearningComponent(learningSpaceId: ValidLearningSpaceId, width: ValidWidth, height: ValidHeight, depth: ValidDepth, x: ValidX, y: ValidY, z: ValidZ, orientation: "InvalidDirection"));
        Assert.That(ex!.ParamName, Is.EqualTo("orientation"));
    }

    /// <summary>
    /// Domain-011: Verify that creating a LearningComponent with valid orientation North succeeds.
    /// </summary>
    [Test]
    [Description("Domain-011: Verify that creating a LearningComponent with valid orientation North succeeds")]
    public void Constructor_WithOrientationNorth_SetsOrientation()
    {
        // Arrange & Act
        var component = new LearningComponent(learningSpaceId: ValidLearningSpaceId, width: ValidWidth, height: ValidHeight, depth: ValidDepth, x: ValidX, y: ValidY, z: ValidZ, orientation: "North");

        // Assert
        Assert.That(component.Orientation, Is.EqualTo("North"));
    }

    /// <summary>
    /// Domain-012: Verify that creating a LearningComponent with valid orientation South succeeds.
    /// </summary>
    [Test]
    [Description("Domain-012: Verify that creating a LearningComponent with valid orientation South succeeds")]
    public void Constructor_WithOrientationSouth_SetsOrientation()
    {
        // Arrange & Act
        var component = new LearningComponent(learningSpaceId: ValidLearningSpaceId, width: ValidWidth, height: ValidHeight, depth: ValidDepth, x: ValidX, y: ValidY, z: ValidZ, orientation: "South");

        // Assert
        Assert.That(component.Orientation, Is.EqualTo("South"));
    }

    /// <summary>
    /// Domain-013: Verify that creating a LearningComponent with valid orientation East succeeds.
    /// </summary>
    [Test]
    [Description("Domain-013: Verify that creating a LearningComponent with valid orientation East succeeds")]
    public void Constructor_WithOrientationEast_SetsOrientation()
    {
        // Arrange & Act
        var component = new LearningComponent(learningSpaceId: ValidLearningSpaceId, width: ValidWidth, height: ValidHeight, depth: ValidDepth, x: ValidX, y: ValidY, z: ValidZ, orientation: "East");

        // Assert
        Assert.That(component.Orientation, Is.EqualTo("East"));
    }

    /// <summary>
    /// Domain-014: Verify that creating a LearningComponent with valid orientation West succeeds.
    /// </summary>
    [Test]
    [Description("Domain-014: Verify that creating a LearningComponent with valid orientation West succeeds")]
    public void Constructor_WithOrientationWest_SetsOrientation()
    {
        // Arrange & Act
        var component = new LearningComponent(learningSpaceId: ValidLearningSpaceId, width: ValidWidth, height: ValidHeight, depth: ValidDepth, x: ValidX, y: ValidY, z: ValidZ, orientation: "West");

        // Assert
        Assert.That(component.Orientation, Is.EqualTo("West"));
    }
}
