using NUnit.Framework;
using UCR.ECCI.PI.ThemePark.Backend.Domain.Entities;

namespace UCR.ECCI.PI.ThemePark.Backend.Domain.Tests.Unit;

/// <summary>
/// Unit tests for the <see cref="LearningComponent"/> entity constructor and validation.
/// Covers intents Domain-001 through Domain-014.
/// </summary>
[TestFixture]
public class LearningComponentTests
{
    private const string ValidLearningSpaceId = "LS-001";
    private const float ValidWidth = 1.5f;
    private const float ValidHeight = 1.0f;
    private const float ValidDepth = 0.5f;
    private const float ValidX = 10.0f;
    private const float ValidY = 5.0f;
    private const float ValidZ = 0.0f;
    private const string ValidOrientation = "North";

    /// <summary>
    /// Domain-001: Verify that a LearningComponent can be created with an auto-generated ID when no ID is provided.
    /// </summary>
    [Test]
    [Description("Domain-001: Constructor without componentId assigns auto-generated ID")]
    public void Constructor_WithoutComponentId_AssignsAutoGeneratedId()
    {
        // Arrange & Act
        var component = new LearningComponent(
            learningSpaceId: ValidLearningSpaceId,
            width: ValidWidth,
            height: ValidHeight,
            depth: ValidDepth,
            x: ValidX,
            y: ValidY,
            z: ValidZ,
            orientation: ValidOrientation);

        // Assert
        Assert.Multiple(() =>
        {
            Assert.That(component.ComponentId, Is.Not.Null);
            Assert.That(component.ComponentId, Is.Not.Empty);
        });
    }

    /// <summary>
    /// Domain-002: Verify that a LearningComponent can be created with an explicitly provided ID.
    /// </summary>
    [Test]
    [Description("Domain-002: Constructor with explicit componentId preserves provided ID")]
    public void Constructor_WithExplicitComponentId_PreservesProvidedId()
    {
        // Arrange & Act
        var component = new LearningComponent(
            componentId: "COMP-12345",
            learningSpaceId: ValidLearningSpaceId,
            width: ValidWidth,
            height: ValidHeight,
            depth: ValidDepth,
            x: ValidX,
            y: ValidY,
            z: ValidZ,
            orientation: ValidOrientation);

        // Assert
        Assert.That(component.ComponentId, Is.EqualTo("COMP-12345"));
    }

    /// <summary>
    /// Domain-003 to Domain-009: Verify that creating a LearningComponent with a negative
    /// dimension or coordinate throws ArgumentException with the correct parameter name.
    /// </summary>
    [TestCase(-1.5f, ValidHeight, ValidDepth, ValidX, ValidY, ValidZ, "width",
        Description = "Domain-003: Negative width throws ArgumentException")]
    [TestCase(ValidWidth, -1.0f, ValidDepth, ValidX, ValidY, ValidZ, "height",
        Description = "Domain-005: Negative height throws ArgumentException")]
    [TestCase(ValidWidth, ValidHeight, -0.5f, ValidX, ValidY, ValidZ, "depth",
        Description = "Domain-006: Negative depth throws ArgumentException")]
    [TestCase(ValidWidth, ValidHeight, ValidDepth, -10.0f, ValidY, ValidZ, "x",
        Description = "Domain-007: Negative X coordinate throws ArgumentException")]
    [TestCase(ValidWidth, ValidHeight, ValidDepth, ValidX, -5.0f, ValidZ, "y",
        Description = "Domain-008: Negative Y coordinate throws ArgumentException")]
    [TestCase(ValidWidth, ValidHeight, ValidDepth, ValidX, ValidY, -1.0f, "z",
        Description = "Domain-009: Negative Z coordinate throws ArgumentException")]
    public void Constructor_NegativeDimensionOrCoordinate_ThrowsArgumentException(
        float width, float height, float depth, float x, float y, float z, string expectedParamName)
    {
        // Arrange & Act
        ArgumentException? caughtException = null;
        try
        {
            new LearningComponent(
                learningSpaceId: ValidLearningSpaceId,
                width: width,
                height: height,
                depth: depth,
                x: x,
                y: y,
                z: z,
                orientation: ValidOrientation);
        }
        catch (ArgumentException ex)
        {
            caughtException = ex;
        }

        // Assert
        Assert.Multiple(() =>
        {
            Assert.That(caughtException, Is.Not.Null, "Expected ArgumentException was not thrown");
            Assert.That(caughtException!.ParamName, Is.EqualTo(expectedParamName));
        });
    }

    /// <summary>
    /// Domain-004: Verify that creating a LearningComponent with zero width throws an ArgumentException.
    /// </summary>
    [Test]
    [Description("Domain-004: Zero width throws ArgumentException")]
    public void Constructor_ZeroWidth_ThrowsArgumentException()
    {
        // Arrange & Act
        ArgumentException? caughtException = null;
        try
        {
            new LearningComponent(
                learningSpaceId: ValidLearningSpaceId,
                width: 0.0f,
                height: ValidHeight,
                depth: ValidDepth,
                x: ValidX,
                y: ValidY,
                z: ValidZ,
                orientation: ValidOrientation);
        }
        catch (ArgumentException ex)
        {
            caughtException = ex;
        }

        // Assert
        Assert.Multiple(() =>
        {
            Assert.That(caughtException, Is.Not.Null, "Expected ArgumentException was not thrown");
            Assert.That(caughtException!.ParamName, Is.EqualTo("width"));
        });
    }

    /// <summary>
    /// Domain-010: Verify that creating a LearningComponent with an invalid orientation
    /// throws ArgumentException with parameter name "orientation".
    /// </summary>
    [TestCase("InvalidDirection", Description = "Domain-010: Invalid orientation throws ArgumentException")]
    public void Constructor_InvalidOrientation_ThrowsArgumentException(string invalidOrientation)
    {
        // Arrange & Act
        ArgumentException? caughtException = null;
        try
        {
            new LearningComponent(
                learningSpaceId: ValidLearningSpaceId,
                width: ValidWidth,
                height: ValidHeight,
                depth: ValidDepth,
                x: ValidX,
                y: ValidY,
                z: ValidZ,
                orientation: invalidOrientation);
        }
        catch (ArgumentException ex)
        {
            caughtException = ex;
        }

        // Assert
        Assert.Multiple(() =>
        {
            Assert.That(caughtException, Is.Not.Null, "Expected ArgumentException was not thrown");
            Assert.That(caughtException!.ParamName, Is.EqualTo("orientation"));
        });
    }

    /// <summary>
    /// Domain-011 to Domain-014: Verify that creating a LearningComponent with each valid
    /// orientation (North, South, East, West) succeeds and the orientation is correctly assigned.
    /// </summary>
    [TestCase("North", Description = "Domain-011: Valid orientation North succeeds")]
    [TestCase("South", Description = "Domain-012: Valid orientation South succeeds")]
    [TestCase("East", Description = "Domain-013: Valid orientation East succeeds")]
    [TestCase("West", Description = "Domain-014: Valid orientation West succeeds")]
    public void Constructor_ValidOrientation_Succeeds(string orientation)
    {
        // Arrange & Act
        var component = new LearningComponent(
            learningSpaceId: ValidLearningSpaceId,
            width: ValidWidth,
            height: ValidHeight,
            depth: ValidDepth,
            x: ValidX,
            y: ValidY,
            z: ValidZ,
            orientation: orientation);

        // Assert
        Assert.That(component.Orientation, Is.EqualTo(orientation));
    }
}
